services:

  _defaults:
    autowire: true
    autoconfigure: true

  Ovesco\APMBSBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Ovesco\APMBSBundle\ApiController\:
    resource: '../../ApiController'
    tags: ['controller.service_arguments']

  Ovesco\APMBSBundle\Listener\MainMenuListener:
    tags:
      - { name: kernel.event_listener, event: netbs.menu.extend, method: onMenuConfigure, priority: 20 }

  Ovesco\APMBSBundle\Security\:
    resource: '../../Security'
    tags:
      - { name: security.voter }